# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_analyst_scrapy_b_scrapy_c_scrapy_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapy_c',
            name='analyst',
        ),
        migrations.AddField(
            model_name='scrapy_c',
            name='company',
            field=models.CharField(default=datetime.datetime(2017, 8, 27, 5, 26, 34, 321000, tzinfo=utc), max_length=100, verbose_name='ICG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapy_c',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 8, 27, 5, 26, 50, 495000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
