# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stock_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_base',
            name='bvps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='esp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='fixedAssets',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='gpr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='holders',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='liquidAssets',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='npr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='outstanding',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='pb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='pe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='perundp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='reserved',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='reservedPerShare',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='rev',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='timeToMarket',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='totalAssets',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='totals',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock_base',
            name='undp',
            field=models.FloatField(),
        ),
    ]
