# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170827_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_detail_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('changepercent', models.FloatField()),
                ('trade', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('settlement', models.FloatField()),
                ('volume', models.IntegerField()),
                ('turnoverratio', models.FloatField()),
                ('amount', models.IntegerField()),
                ('per', models.FloatField()),
                ('pb', models.FloatField()),
                ('mktcap', models.FloatField()),
                ('nmc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_detail_today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('changepercent', models.FloatField()),
                ('trade', models.FloatField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('settlement', models.FloatField()),
                ('volume', models.IntegerField()),
                ('turnoverratio', models.FloatField()),
                ('amount', models.IntegerField()),
                ('per', models.FloatField()),
                ('pb', models.FloatField()),
                ('mktcap', models.FloatField()),
                ('nmc', models.FloatField()),
            ],
        ),
    ]
