# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stock_detail_history_stock_detail_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_detail_history',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 28)),
        ),
    ]
