# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-28 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_stock_detail_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSH_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('date', models.CharField(max_length=32)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Power_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100, verbose_name='ICG')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapy_d',
            name='analyst',
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='company',
            field=models.CharField(default='ICG', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='delta_30_date',
            field=models.DateField(default=datetime.date(2017, 8, 28)),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='name',
            field=models.CharField(default='ICG', max_length=100),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='price_delta_30_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='price_publish_date',
            field=models.FloatField(default=0.0),
        ),
    ]
