# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-28 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170828_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapy_d',
            name='delta_180_date',
            field=models.DateField(default=datetime.date(2017, 8, 28)),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='delta_60_date',
            field=models.DateField(default=datetime.date(2017, 8, 28)),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='delta_90_date',
            field=models.DateField(default=datetime.date(2017, 8, 28)),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='price_delta_180_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='price_delta_60_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='price_delta_90_date',
            field=models.FloatField(default=0.0),
        ),
    ]
