# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170828_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst_power_today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('power_30', models.FloatField()),
                ('power_60', models.FloatField()),
                ('power_90', models.FloatField()),
                ('power_180', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='charge_delta_180_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='charge_delta_30_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='charge_delta_60_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scrapy_d',
            name='charge_delta_90_date',
            field=models.FloatField(default=0.0),
        ),
    ]
