# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170828_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst_power_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('power_30', models.FloatField()),
                ('power_60', models.FloatField()),
                ('power_90', models.FloatField()),
                ('power_180', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
