# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_analyst_power_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_180_date',
            field=models.DateField(default=datetime.date(2017, 8, 31)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_30_date',
            field=models.DateField(default=datetime.date(2017, 8, 31)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_60_date',
            field=models.DateField(default=datetime.date(2017, 8, 31)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_90_date',
            field=models.DateField(default=datetime.date(2017, 8, 31)),
        ),
        migrations.AlterField(
            model_name='stock_detail_history',
            name='date',
            field=models.DateField(default=datetime.date(2017, 8, 31)),
        ),
    ]
