# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170831_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapy_d',
            name='boolean_str',
            field=models.IntegerField(default=1),
        ),
    ]
