# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_scrapy_d_boolean_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst_power_today',
            name='power_180_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyst_power_today',
            name='power_30_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyst_power_today',
            name='power_60_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analyst_power_today',
            name='power_90_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_180_date',
            field=models.DateField(default=datetime.date(2017, 9, 3)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_30_date',
            field=models.DateField(default=datetime.date(2017, 9, 3)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_60_date',
            field=models.DateField(default=datetime.date(2017, 9, 3)),
        ),
        migrations.AlterField(
            model_name='scrapy_d',
            name='delta_90_date',
            field=models.DateField(default=datetime.date(2017, 9, 3)),
        ),
        migrations.AlterField(
            model_name='stock_detail_history',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 3)),
        ),
    ]
